version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Exposes frontend on port 3000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Exposes backend on port 5000
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
